const defaultValuesSpanish = [
  { id: 'dom_open', time: 'closed', label: 'Domingo' },
  { id: 'dom_close', time: 'closed', label: 'Domingo' },
  { id: 'lun_open', time: '09:00:00', label: 'Lunes' },
  { id: 'lun_close', time: '17:00:00', label: 'Lunes' },
  { id: 'mar_open', time: '09:00:00', label: 'Martes' },
  { id: 'mar_close', time: '17:00:00', label: 'Martes' },
  { id: 'mie_open', time: '09:00:00', label: 'Miércoles' },
  { id: 'mie_close', time: '17:00:00', label: 'Miércoles' },
  { id: 'jue_open', time: '09:00:00', label: 'Jueves' },
  { id: 'jue_close', time: '17:00:00', label: 'Jueves' },
  { id: 'vie_open', time: '09:00:00', label: 'Viernes' },
  { id: 'vie_close', time: '17:00:00', label: 'Viernes' },
  { id: 'sab_open', time: 'closed', label: 'Sábado' },
  { id: 'sab_close', time: 'closed', label: 'Sábado' },
];

const defaultValuesThai = [
  { id: 'sun_open', time: 'closed', label: 'วันอาทิตย์' },
  { id: 'sun_close', time: 'closed', label: 'วันอาทิตย์' },
  { id: 'mon_open', time: '09:00:00', label: 'วันจันทร์' },
  { id: 'mon_close', time: '17:00:00', label: 'วันจันทร์' },
  { id: 'tue_open', time: '09:00:00', label: 'วันอังคาร' },
  { id: 'tue_close', time: '17:00:00', label: 'วันอังคาร' },
  { id: 'wed_open', time: '09:00:00', label: 'วันพุธ' },
  { id: 'wed_close', time: '17:00:00', label: 'วันพุธ' },
  { id: 'thu_open', time: '09:00:00', label: 'วันพฤหัสบดี' },
  { id: 'thu_close', time: '17:00:00', label: 'วันพฤหัสบดี' },
  { id: 'fri_open', time: '09:00:00', label: 'วันศุกร์' },
  { id: 'fri_close', time: '17:00:00', label: 'วันศุกร์' },
  { id: 'sat_open', time: 'closed', label: 'วันเสาร์' },
  { id: 'sat_close', time: 'closed', label: 'วันเสาร์' },
];

const defaultValuesFrench = [
  { id: 'dimanche_ouvert', time: 'closed', label: 'Dimanche' },
  { id: 'dimanche_fermé', time: 'closed', label: 'Dimanche' },
  { id: 'lundi_ouvert', time: '09:00:00', label: 'Lundi' },
  { id: 'lundi_fermé', time: '17:00:00', label: 'Lundi' },
  { id: 'mardi_ouvert', time: '09:00:00', label: 'Mardi' },
  { id: 'mardi_fermé', time: '17:00:00', label: 'Mardi' },
  { id: 'mercredi_ouvert', time: '09:00:00', label: 'Mercredi' },
  { id: 'mercredi_fermé', time: '17:00:00', label: 'Mercredi' },
  { id: 'jeudi_ouvert', time: '09:00:00', label: 'Jeudi' },
  { id: 'jeudi_fermé', time: '17:00:00', label: 'Jeudi' },
  { id: 'vendredi_ouvert', time: '09:00:00', label: 'Vendredi' },
  { id: 'vendredi_fermé', time: '17:00:00', label: 'Vendredi' },
  { id: 'samedi_ouvert', time: 'closed', label: 'Samedi' },
  { id: 'samedi_fermé', time: 'closed', label: 'Samedi' },
];

const defaultValues = [
  { id: 'sun_open', time: 'closed', label: 'Sunday' },
  { id: 'sun_close', time: 'closed', label: 'Sunday' },
  { id: 'mon_open', time: '09:00:00', label: 'Monday' },
  { id: 'mon_close', time: '17:00:00', label: 'Monday' },
  { id: 'tue_open', time: '09:00:00', label: 'Tuesday' },
  { id: 'tue_close', time: '17:00:00', label: 'Tuesday' },
  { id: 'wed_open', time: '09:00:00', label: 'Wednesday' },
  { id: 'wed_close', time: '17:00:00', label: 'Wednesday' },
  { id: 'thu_open', time: '09:00:00', label: 'Thursday' },
  { id: 'thu_close', time: '17:00:00', label: 'Thursday' },
  { id: 'fri_open', time: '09:00:00', label: 'Friday' },
  { id: 'fri_close', time: '17:00:00', label: 'Friday' },
  { id: 'sat_open', time: 'closed', label: 'Saturday' },
  { id: 'sat_close', time: 'closed', label: 'Saturday' },
];
